name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: swa-starkadvisor-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          # Evita que CRA/ESLint falle el build por warnings en CI
          CI: false
          DISABLE_ESLINT_PLUGIN: true
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_PLANT_02A26BE0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # para comentarios en PR
          action: upload

          ###### Configuración del repo/build (ajusta si tu app está en subcarpeta) ######
          app_location: "/"                 # Ruta del código de la app ("/" si está en la raíz)
          api_location: ""                  # Ruta de API (opcional)
          output_location: "build"          # Carpeta generada por el build

          # Fuerza el comando de build para CRA con CI=false (por si Oryx no toma el env)
          app_build_command: "CI=false npm run build"
          ###### Fin configuración ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_PLANT_02A26BE0F }}
          action: close
